version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: kb_postgres_dev
    environment:
      POSTGRES_DB: knowledge_base
      POSTGRES_USER: kb_user
      POSTGRES_PASSWORD: kb_password
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - kb_network_dev

  # Redis 缓存和消息队列
  redis:
    image: redis:7-alpine
    container_name: kb_redis_dev
    command: redis-server --appendonly yes --requirepass redis_password
    volumes:
      - redis_data_dev:/data
    ports:
      - "6380:6379"
    networks:
      - kb_network_dev

  # Elasticsearch 搜索引擎
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: kb_elasticsearch_dev
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch_data_dev:/usr/share/elasticsearch/data
    ports:
      - "9201:9200"
    networks:
      - kb_network_dev

volumes:
  postgres_data_dev:
  redis_data_dev:
  elasticsearch_data_dev:

networks:
  kb_network_dev:
    driver: bridge