# Generated by Django 4.2.7 on 2025-09-20 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="模板名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "version",
                    models.CharField(
                        default="1.0.0", max_length=20, verbose_name="版本"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("active", "激活"),
                            ("archived", "归档"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "definition",
                    models.JSONField(default=dict, verbose_name="工作流定义"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "execution_count",
                    models.IntegerField(default=0, verbose_name="执行次数"),
                ),
                (
                    "success_count",
                    models.IntegerField(default=0, verbose_name="成功次数"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_workflows",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流模板",
                "verbose_name_plural": "工作流模板",
                "db_table": "workflow_template",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="调度名称")),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("once", "一次性"),
                            ("interval", "间隔"),
                            ("cron", "Cron表达式"),
                            ("event", "事件触发"),
                        ],
                        max_length=20,
                        verbose_name="调度类型",
                    ),
                ),
                (
                    "schedule_config",
                    models.JSONField(default=dict, verbose_name="调度配置"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "激活"),
                            ("paused", "暂停"),
                            ("disabled", "禁用"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(default=dict, verbose_name="默认输入数据"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="上次执行时间"
                    ),
                ),
                (
                    "next_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="下次执行时间"
                    ),
                ),
                (
                    "execution_count",
                    models.IntegerField(default=0, verbose_name="执行次数"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="workflow.workflowtemplate",
                        verbose_name="工作流模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流调度",
                "verbose_name_plural": "工作流调度",
                "db_table": "workflow_schedule",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("paused", "暂停"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("normal", "普通"),
                            ("high", "高"),
                            ("urgent", "紧急"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="优先级",
                    ),
                ),
                ("input_data", models.JSONField(default=dict, verbose_name="输入数据")),
                (
                    "output_data",
                    models.JSONField(default=dict, verbose_name="输出数据"),
                ),
                ("context", models.JSONField(default=dict, verbose_name="执行上下文")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "max_retries",
                    models.IntegerField(default=3, verbose_name="最大重试次数"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="workflow.workflowtemplate",
                        verbose_name="工作流模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流执行",
                "verbose_name_plural": "工作流执行",
                "db_table": "workflow_execution",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkflowVariable",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="变量名")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "全局"),
                            ("template", "模板"),
                            ("execution", "执行实例"),
                        ],
                        max_length=20,
                        verbose_name="作用域",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "字符串"),
                            ("number", "数字"),
                            ("boolean", "布尔值"),
                            ("json", "JSON对象"),
                            ("file", "文件"),
                        ],
                        default="string",
                        max_length=20,
                        verbose_name="数据类型",
                    ),
                ),
                ("value", models.JSONField(verbose_name="变量值")),
                (
                    "default_value",
                    models.JSONField(blank=True, null=True, verbose_name="默认值"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="是否加密"),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="是否必需"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="workflow.workflowexecution",
                        verbose_name="工作流执行",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="workflow.workflowtemplate",
                        verbose_name="工作流模板",
                    ),
                ),
            ],
            options={
                "verbose_name": "工作流变量",
                "verbose_name_plural": "工作流变量",
                "db_table": "workflow_variable",
                "ordering": ["name"],
                "unique_together": {
                    ("name", "scope", "execution"),
                    ("name", "scope", "template"),
                },
            },
        ),
        migrations.CreateModel(
            name="NodeExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_id", models.CharField(max_length=100, verbose_name="节点ID")),
                ("node_type", models.CharField(max_length=50, verbose_name="节点类型")),
                (
                    "node_name",
                    models.CharField(max_length=200, verbose_name="节点名称"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("input_data", models.JSONField(default=dict, verbose_name="输入数据")),
                (
                    "output_data",
                    models.JSONField(default=dict, verbose_name="输出数据"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "retry_count",
                    models.IntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "workflow_execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_executions",
                        to="workflow.workflowexecution",
                        verbose_name="工作流执行",
                    ),
                ),
            ],
            options={
                "verbose_name": "节点执行",
                "verbose_name_plural": "节点执行",
                "db_table": "node_execution",
                "ordering": ["started_at"],
                "unique_together": {("workflow_execution", "node_id")},
            },
        ),
    ]
