# Generated by Django 4.2.7 on 2025-09-20 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="查询内容"
                    ),
                ),
                (
                    "search_count",
                    models.PositiveIntegerField(default=1, verbose_name="搜索次数"),
                ),
                (
                    "last_searched",
                    models.DateTimeField(auto_now=True, verbose_name="最后搜索时间"),
                ),
            ],
            options={
                "verbose_name": "热门搜索",
                "verbose_name_plural": "热门搜索",
                "db_table": "kb_popular_searches",
                "ordering": ["-search_count", "-last_searched"],
            },
        ),
        migrations.CreateModel(
            name="SearchQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500, verbose_name="查询内容")),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="过滤条件"),
                ),
                (
                    "results_count",
                    models.PositiveIntegerField(default=0, verbose_name="结果数量"),
                ),
                (
                    "execution_time",
                    models.FloatField(default=0.0, verbose_name="执行时间(秒)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_queries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "搜索查询",
                "verbose_name_plural": "搜索查询",
                "db_table": "kb_search_queries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="kb_search_q_user_id_82948e_idx",
                    ),
                    models.Index(fields=["query"], name="kb_search_q_query_4a8998_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待索引"),
                            ("indexing", "索引中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "indexed_content",
                    models.TextField(blank=True, verbose_name="索引内容"),
                ),
                ("keywords", models.TextField(blank=True, verbose_name="关键词")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_index",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "搜索索引",
                "verbose_name_plural": "搜索索引",
                "db_table": "kb_search_indexes",
                "indexes": [
                    models.Index(
                        fields=["status"], name="kb_search_i_status_3d26eb_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="kb_search_i_updated_556a7a_idx"
                    ),
                ],
            },
        ),
    ]
